### PR TITLE
Added few sites to the list

### PR DESCRIPTION
**Pull request by MAT978**
Few sites added to the list.
IMHO some have no interest to be added like: cdn, help...
And some have their own way for reporting issues: forum, extensions, issues...
Thanks

### CODE REVIEW

**Comment by mbabker** [comment]
Like we did for the Framework and Issue Tracker, I'd say add a link for the JED pointing to their JIRA system (I don't know if we can direct link to the issue form but that's close enough).  CDN and Help as they aren't public facing sites (well help's offline and the proxy is only accessed within the CMS), I agree with you on that.  JoomlaCode I wouldn't even bother with at this point; it's a lost cause.

**Comment by Hutchy68** [comment]
I found(after a hunt and search) the link to the issue tracker the JED is using. Added to the file changes.

**Comment by MAT978** [comment]
@Hutchy68  HA...
I was searching for it and even had to ask Matt and Tessa ;)

**Comment by matthewbaylor** [comment]
FYI
joomla__extensions_directory

**Comment by MAT978** [comment]
Thank @matthewbaylor 
I was not logged :flushed:

**Comment by matthewbaylor** [comment]
It was public but turned into everyone submitting everything BUT issues. Set to registered it gets used as intended for the most part.

**Pull request merged**
